name: Action test on MacOS

on:
  push:
  workflow_dispatch:

jobs:
  test-default:
    runs-on: macos-latest
    steps:
      - uses: GuillaumeFalourd/create-other-repo-branch-action@main
        with:
          repository_owner: GuillaumeFalourd
          repository_name: poc-github-actions
          new_branch_name: test-2
          access_token: ${{ secrets.ACCESS_TOKEN}}
