name: Action test on Ubuntu

on: [workflow_dispatch]

jobs:
  test-default:
    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/create-other-repo-branch-action@main
        with:
          repository_owner: GuillaumeFalourd
          repository_name: poc-github-actions
          new_branch_name: test-1
          access_token: ${{ secrets.ACCESS_TOKEN}}

  test-specific:
    runs-on: ubuntu-latest
    needs: test-default
    steps:
      - uses: GuillaumeFalourd/create-other-repo-branch-action@main
        with:
          repository_owner: GuillaumeFalourd
          repository_name: poc-github-actions
          new_branch_name: test-1.1
          new_branch_ref: test-1
          access_token: ${{ secrets.ACCESS_TOKEN}}